# Generated by Django 5.0.6 on 2024-06-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberregister',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
